<html xmlns:tp="http://schemas.datacontract.org/2004/07/Microsoft.VisualStudio.TestPlatform.Extensions.HtmlLogger.ObjectModel" xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
  <body>
    <h1>Test run details</h1>
    <div class="summary">
      <div class="block"><span>Total tests</span><div class="total-tests">15</div><br></div>
      <div class="block"><span>Passed  : </span><span class="passedTests">0</span><br><span>Failed  : </span><span class="failedTests">15</span><br><span>Skipped : </span><span class="skippedTests">0</span><br></div>
      <div class="block"><span>Pass percentage</span><div class="pass-percentage">0 %</div><br></div>
      <div class="block"><span>Run duration</span><div class="test-run-time">6m 12s</div><br></div><br></div>
    <h2>Failed Results</h2><details open=""><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="-2086809624-failedResult">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>33s 145ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>25s 78ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Server.ConcurrentRequestsTests.&lt;&gt;c__DisplayClass3_1.&lt;&lt;MultipleConcurrentFileRequests_ReturnsCorrectResponses&gt;b__0&gt;d.MoveNext() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 78
--- End of stack trace from previous location ---
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 84
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource&lt;System.Int32&gt;.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource&lt;TResult&gt;.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource&lt;TResult&gt;.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>33s 562ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Microsoft.Playwright.PlaywrightException : net::ERR_CONNECTION_RESET at https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt
Call log:
  - navigating to "https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 70
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 107
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>37s 130ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 130
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 154
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>36s 202ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 88
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>1m 6s</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 62
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 606ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 88ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '945cbc43-cee8-4b70-b30c-194e596d6a23'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><h2>All Results</h2><details><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="-2086809624">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>33s 145ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>25s 78ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Server.ConcurrentRequestsTests.&lt;&gt;c__DisplayClass3_1.&lt;&lt;MultipleConcurrentFileRequests_ReturnsCorrectResponses&gt;b__0&gt;d.MoveNext() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 78
--- End of stack trace from previous location ---
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 84
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource&lt;System.Int32&gt;.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource&lt;TResult&gt;.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource&lt;TResult&gt;.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>1ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 43
   at InvokeStub_FileFetchingTests..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>33s 562ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Microsoft.Playwright.PlaywrightException : net::ERR_CONNECTION_RESET at https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt
Call log:
  - navigating to "https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 70
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 107
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>37s 130ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 130
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 154
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>36s 202ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 88
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>1m 6s</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 62
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 606ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 88ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '945cbc43-cee8-4b70-b30c-194e596d6a23'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><div>
      <h2>Informational messages</h2><span>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 9.0.0-rc.1.24431.7)</span><br><span>[xUnit.net 00:00:00.47]   Discovering: FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.50]   Discovered:  FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.50]   Starting:    FileSyncServer.Tests</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 11b2eb20-194c-4320-aa1b-9a12a3d5eb50</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 11b2eb20-194c-4320-aa1b-9a12a3d5eb50</span><br><span>[xUnit.net 00:00:46.66]       Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:00:46.66]       Stack Trace:</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:00:46.66]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:00:46.66]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(136,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:00:46.66]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:01:11.74]       System.Net.Http.HttpRequestException : An error occurred while sending the request.</span><br><span>[xUnit.net 00:01:11.74]       ---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..</span><br><span>[xUnit.net 00:01:11.74]       -------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.</span><br><span>[xUnit.net 00:01:11.74]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)</span><br><span>[xUnit.net 00:01:11.74]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(78,0): at Server.ConcurrentRequestsTests.&lt;&gt;c__DisplayClass3_1.&lt;&lt;MultipleConcurrentFileRequests_ReturnsCorrectResponses&gt;b__0&gt;d.MoveNext()</span><br><span>[xUnit.net 00:01:11.74]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:01:11.74]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(84,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:01:11.74]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:01:11.74]         ----- Inner Stack Trace -----</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource&lt;System.Int32&gt;.GetResult(Int16 token)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)</span><br><span>[xUnit.net 00:01:11.74]            at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource&lt;TResult&gt;.GetResult(Int16 token)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)</span><br><span>[xUnit.net 00:01:11.74]            at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource&lt;TResult&gt;.GetResult(Int16 token)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)</span><br><span>[xUnit.net 00:01:11.74]            at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)</span><br><span>[xUnit.net 00:01:11.74]         ----- Inner Stack Trace -----</span><br><span>[xUnit.net 00:01:11.74]         </span><br><span>[xUnit.net 00:01:11.75]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.75]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.75]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.75]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)</span><br><span>[xUnit.net 00:01:11.75]            at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)</span><br><span>[xUnit.net 00:01:11.75]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.75]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.75]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.75]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.75]            at InvokeStub_FileFetchingTests..ctor(Object, Span`1)</span><br><span>[xUnit.net 00:01:11.75]            at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</span><br><span>[xUnit.net 00:01:11.76]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.76]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.76]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.76]            at InvokeStub_FileFetchingTests..ctor(Object, Span`1)</span><br><span>[xUnit.net 00:01:11.76]            at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</span><br><span>[xUnit.net 00:01:11.76]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.76]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.76]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.76]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.76]            at InvokeStub_FileFetchingTests..ctor(Object, Span`1)</span><br><span>[xUnit.net 00:01:11.76]            at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</span><br><span>[xUnit.net 00:01:11.77]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.77]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.77]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.77]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.77]            at InvokeStub_FileFetchingTests..ctor(Object, Span`1)</span><br><span>[xUnit.net 00:01:11.77]            at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</span><br><span>[xUnit.net 00:01:11.78]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.78]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.78]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.78]            at InvokeStub_FileFetchingTests..ctor(Object, Span`1)</span><br><span>[xUnit.net 00:01:11.78]            at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</span><br><span>[xUnit.net 00:01:11.78]       Expected Process.GetProcessesByName("RemoteWebViewService").Length to be greater than 0 because Server process should be running., but found 0.</span><br><span>[xUnit.net 00:01:11.78]       Stack Trace:</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:11.78]            at FluentAssertions.Numeric.NumericAssertions`2.BeGreaterThan(T expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:11.78]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(43,0): at Server.FileFetchingTests..ctor(ServerFixture serverFixture, ClientFixture clientFixture)</span><br><span>[xUnit.net 00:01:11.78]            at InvokeStub_FileFetchingTests..ctor(Object, Span`1)</span><br><span>[xUnit.net 00:01:11.78]            at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</span><br><span>Client Output: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.")</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 2/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 2/768 (Min: 0)</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 64d79816-787d-4037-bf41-59ba489a0589</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 64d79816-787d-4037-bf41-59ba489a0589</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = True</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 3/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 3/768 (Min: 0)</span><br><span>[xUnit.net 00:01:57.86]       Microsoft.Playwright.PlaywrightException : net::ERR_CONNECTION_RESET at https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt
Call log:
  - navigating to "https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt", waiting until "networkidle"</span><br><span>[xUnit.net 00:01:57.86]       Stack Trace:</span><br><span>[xUnit.net 00:01:57.86]         /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)</span><br><span>[xUnit.net 00:01:57.86]         /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)</span><br><span>[xUnit.net 00:01:57.86]         /_/src/Playwright/Core/Frame.cs(793,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)</span><br><span>[xUnit.net 00:01:57.86]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(70,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:01:57.86]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(107,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:01:57.86]         --- End of stack trace from previous location ---</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:02:34.99]       System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/64d79816-787d-4037-bf41-59ba489a0589/testfile.txt", waiting until "networkidle"</span><br><span>[xUnit.net 00:02:34.99]       Stack Trace:</span><br><span>[xUnit.net 00:02:34.99]         /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)</span><br><span>[xUnit.net 00:02:34.99]         /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)</span><br><span>[xUnit.net 00:02:34.99]         /_/src/Playwright/Core/Frame.cs(793,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)</span><br><span>[xUnit.net 00:02:34.99]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(130,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:02:34.99]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(154,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:02:34.99]         --- End of stack trace from previous location ---</span><br><span>Client Output: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.")</span><br><span>Killing process: RemoteWebViewService (ID: 21632)</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 7965e17c-8b53-49fb-9ae5-da3580f0c0e6</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 7965e17c-8b53-49fb-9ae5-da3580f0c0e6</span><br><span>Server Output: Server cache enabled = False</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:03:23.72]       Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:03:23.72]       Stack Trace:</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:03:23.72]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:03:23.72]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs(88,0): at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:03:23.72]         --- End of stack trace from previous location ---</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = True</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 0/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 0/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:04:29.89]       Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:04:29.89]       Stack Trace:</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:04:29.89]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:04:29.89]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs(62,0): at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:04:29.89]         --- End of stack trace from previous location ---</span><br><span>Killing process: RemoteWebViewService (ID: 12140)</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 472e3d42-606d-4fd6-ac68-940e8cd4f5bd</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 472e3d42-606d-4fd6-ac68-940e8cd4f5bd</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 2b43fb04-7723-46ee-b2ee-6f6eb4760ead</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 2b43fb04-7723-46ee-b2ee-6f6eb4760ead</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: e8cd5ea4-b9cc-40a1-bcd7-f327728c5e15</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: e8cd5ea4-b9cc-40a1-bcd7-f327728c5e15</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: fbbeeedb-7fea-4150-8cbf-8c586db22b3a</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: fbbeeedb-7fea-4150-8cbf-8c586db22b3a</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 9d4845e3-43fa-4830-9a07-0d54649d7735</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 9d4845e3-43fa-4830-9a07-0d54649d7735</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 3a713a0f-238b-4a1c-a90c-df385cc78fb4</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test1.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test2.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test3.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test4.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test5.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 3a713a0f-238b-4a1c-a90c-df385cc78fb4</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 2/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 2/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Disposed client with clientId: 472e3d42-606d-4fd6-ac68-940e8cd4f5bd</span><br><span>Disposed client with clientId: 2b43fb04-7723-46ee-b2ee-6f6eb4760ead</span><br><span>Disposed client with clientId: e8cd5ea4-b9cc-40a1-bcd7-f327728c5e15</span><br><span>Disposed client with clientId: fbbeeedb-7fea-4150-8cbf-8c586db22b3a</span><br><span>Disposed client with clientId: 9d4845e3-43fa-4830-9a07-0d54649d7735</span><br><span>[xUnit.net 00:05:27.02]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:05:27.02]       Stack Trace:</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:05:27.02]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:05:27.02]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(124,0): at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics()</span><br><span>[xUnit.net 00:05:27.02]         --- End of stack trace from previous location ---</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 945cbc43-cee8-4b70-b30c-194e596d6a23</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 945cbc43-cee8-4b70-b30c-194e596d6a23</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: cf507303-266d-4b15-a46f-e4ae456a8ecd</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: cf507303-266d-4b15-a46f-e4ae456a8ecd</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: eadd8de7-ce0f-4219-b63c-5d84fba9d4d7</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: eadd8de7-ce0f-4219-b63c-5d84fba9d4d7</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: e049f794-c715-4b77-98dc-03cc4a4393d4</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: e049f794-c715-4b77-98dc-03cc4a4393d4</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: bbad5ab0-3f7e-4381-89fe-38c547f28c12</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test2.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: bbad5ab0-3f7e-4381-89fe-38c547f28c12</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test10.txt</span><br><span>Disposed client with clientId: 945cbc43-cee8-4b70-b30c-194e596d6a23</span><br><span>Disposed client with clientId: cf507303-266d-4b15-a46f-e4ae456a8ecd</span><br><span>Disposed client with clientId: eadd8de7-ce0f-4219-b63c-5d84fba9d4d7</span><br><span>Disposed client with clientId: e049f794-c715-4b77-98dc-03cc4a4393d4</span><br><span>Disposed client with clientId: bbad5ab0-3f7e-4381-89fe-38c547f28c12</span><br><span>[xUnit.net 00:06:11.59]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '945cbc43-cee8-4b70-b30c-194e596d6a23'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:11.59]       Stack Trace:</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:11.59]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:11.59]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(196,0): at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:06:11.59]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:06:11.60]   Finished:    FileSyncServer.Tests</span><br></div>
    <div>
      <h2>Error and Warning messages</h2><span>[xUnit.net 00:00:46.66]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:01:11.74]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:01:11.75]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt") [FAIL]</span><br><span>[xUnit.net 00:01:11.75]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt") [FAIL]</span><br><span>[xUnit.net 00:01:11.76]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt") [FAIL]</span><br><span>[xUnit.net 00:01:11.76]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt") [FAIL]</span><br><span>[xUnit.net 00:01:11.77]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt") [FAIL]</span><br><span>[xUnit.net 00:01:11.78]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt") [FAIL]</span><br><span>[xUnit.net 00:01:11.78]     Server.FileFetchingTests.GetLargeFile_ReturnsFileContent [FAIL]</span><br><span>[xUnit.net 00:01:57.86]     FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:02:34.99]     FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:03:23.72]     FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:04:29.89]     FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:05:27.02]     Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics [FAIL]</span><br><span>[xUnit.net 00:06:11.59]     Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br></div>
  </body>
  <style>
        body { font-family: Calibri, Verdana, Arial, sans-serif; background-color: White; color: Black; }
        h2 {
        margin-top: 15px;
        margin-bottom:10px;
        }
        pre {
        white-space: pre-wrap;
        }
        .summary {font-family:monospace;
        display: -webkit-flex; /* Safari */
        -webkit-flex-wrap: wrap; /* Safari 6.1+ */
        display: flex;
        flex-wrap: wrap;
        }
        .row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#d7e9fa;
        }
        .list-row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#ffffff;
        }
        .inner-row{
        border: 2px solid #ffffff;
        padding-left:1%;
        margin-left:1%;
        background-color:#ffffff;
        }
        .block{
        width : 150px;
        }
        .leaf-division{
        border: 2px solid #ffffff;
        background-color:#e6eff7;
        }
        .pass { color: #0c0; }
        .fail { color: #c00; }
        .error-message { color : brown; }
        .error-stack-trace { color: brown; }
        .duration {float:right;padding-right:1%;}
        .total-tests { font-size : 30px}
        .test-run-time { font-size : 30px}
        .pass-percentage { font-size : 30px}
        .error-info{
        margin-left:16px;
        }
      </style>
</html>