<html xmlns:tp="http://schemas.datacontract.org/2004/07/Microsoft.VisualStudio.TestPlatform.Extensions.HtmlLogger.ObjectModel" xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
  <body>
    <h1>Test run details</h1>
    <div class="summary">
      <div class="block"><span>Total tests</span><div class="total-tests">15</div><br></div>
      <div class="block"><span>Passed  : </span><span class="passedTests">2</span><br><span>Failed  : </span><span class="failedTests">13</span><br><span>Skipped : </span><span class="skippedTests">0</span><br></div>
      <div class="block"><span>Pass percentage</span><div class="pass-percentage">13 %</div><br></div>
      <div class="block"><span>Run duration</span><div class="test-run-time">8m 36s</div><br></div><br></div>
    <h2>Failed Results</h2><details open=""><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="1978447131-failedResult">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 817ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 76ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '1d5adfdd-eb68-4cb4-ad86-a4b8a27e90e7'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>36s 155ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 88
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>36s 80ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 62
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>32s 380ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 65ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 89
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>32s 26ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>32s 35ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>32s 35ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>32s 26ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>32s 31ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>32s 30ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>32s 53ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 106
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><h2>All Results</h2><details><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="1978447131">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 817ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 76ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '1d5adfdd-eb68-4cb4-ad86-a4b8a27e90e7'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>36s 155ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 88
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>36s 80ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 62
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>32s 380ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 65ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 89
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>32s 26ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>32s 35ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>32s 35ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>32s 26ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>32s 31ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>32s 30ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>32s 53ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 106
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="pass">✔</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>8s 579ms</span><br></div>
          </div>
          <div class="error-info"></div>
        </div>
        <div class="leaf-division">
          <div><span class="pass">✔</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>5s 841ms</span><br></div>
          </div>
          <div class="error-info"></div>
        </div>
      </div></details><div>
      <h2>Informational messages</h2><span>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 9.0.0-rc.1.24431.7)</span><br><span>[xUnit.net 00:00:00.46]   Discovering: FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.49]   Discovered:  FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.49]   Starting:    FileSyncServer.Tests</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 918403b4-1cc4-45af-9102-147c01c112c6</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 918403b4-1cc4-45af-9102-147c01c112c6</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: a0b5e96e-9add-41a7-8e8d-7dca51dd21f6</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: a0b5e96e-9add-41a7-8e8d-7dca51dd21f6</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 71b1b0a8-8c6b-4931-92fc-ea27a68c00d3</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 71b1b0a8-8c6b-4931-92fc-ea27a68c00d3</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 2eddbb2c-eed0-4f6d-8066-3f14d1d8ca89</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 2eddbb2c-eed0-4f6d-8066-3f14d1d8ca89</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: e672b3bc-5242-4aa9-8cd2-d998bd4d96c5</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: e672b3bc-5242-4aa9-8cd2-d998bd4d96c5</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 722aadae-d54e-4eb3-9c0f-65068611f10b</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test1.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test2.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test3.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test4.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test5.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 722aadae-d54e-4eb3-9c0f-65068611f10b</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Disposed client with clientId: 918403b4-1cc4-45af-9102-147c01c112c6</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: a0b5e96e-9add-41a7-8e8d-7dca51dd21f6</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 71b1b0a8-8c6b-4931-92fc-ea27a68c00d3</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 2eddbb2c-eed0-4f6d-8066-3f14d1d8ca89</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: e672b3bc-5242-4aa9-8cd2-d998bd4d96c5</span><br><span>[xUnit.net 00:00:58.47]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:00:58.47]       Stack Trace:</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:00:58.47]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:00:58.47]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(124,0): at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics()</span><br><span>[xUnit.net 00:00:58.47]         --- End of stack trace from previous location ---</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 1d5adfdd-eb68-4cb4-ad86-a4b8a27e90e7</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 1d5adfdd-eb68-4cb4-ad86-a4b8a27e90e7</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 00190392-44a9-4dfc-a794-e23f81c590b8</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 00190392-44a9-4dfc-a794-e23f81c590b8</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 323bc0f1-398c-4454-916a-1c347ea50ccc</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 323bc0f1-398c-4454-916a-1c347ea50ccc</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 6a07ee0d-e76d-410a-89b5-3e0ca70dbec0</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 6a07ee0d-e76d-410a-89b5-3e0ca70dbec0</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: c2164b8c-0ac4-4a27-b7d1-d338c863b566</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test1.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: c2164b8c-0ac4-4a27-b7d1-d338c863b566</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test10.txt</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 1d5adfdd-eb68-4cb4-ad86-a4b8a27e90e7</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 00190392-44a9-4dfc-a794-e23f81c590b8</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 323bc0f1-398c-4454-916a-1c347ea50ccc</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 6a07ee0d-e76d-410a-89b5-3e0ca70dbec0</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: c2164b8c-0ac4-4a27-b7d1-d338c863b566</span><br><span>[xUnit.net 00:01:42.88]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '1d5adfdd-eb68-4cb4-ad86-a4b8a27e90e7'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:01:42.88]       Stack Trace:</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:42.88]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:42.88]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(196,0): at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:01:42.88]         --- End of stack trace from previous location ---</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 9d42871a-92db-4b57-a9a5-e7f14906719b</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 9d42871a-92db-4b57-a9a5-e7f14906719b</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Server cache enabled = False</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:02:31.50]       Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:02:31.50]       Stack Trace:</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:02:31.50]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:02:31.50]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs(88,0): at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:02:31.50]         --- End of stack trace from previous location ---</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = True</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:03:07.58]       Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:03:07.58]       Stack Trace:</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:03:07.58]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:03:07.58]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs(62,0): at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:03:07.58]         --- End of stack trace from previous location ---</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 4133afc7-d67d-49c3-bc7e-eb43cde7ee46</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 4133afc7-d67d-49c3-bc7e-eb43cde7ee46</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>[xUnit.net 00:03:52.43]       Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:03:52.43]       Stack Trace:</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:03:52.43]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:03:52.43]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(136,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:03:52.43]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:04:24.50]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:04:24.50]       Stack Trace:</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:04:24.50]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:04:24.50]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(89,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:04:24.50]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:04:56.53]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:04:56.53]       Stack Trace:</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:04:56.53]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:04:56.53]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:04:56.53]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:05:28.56]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:05:28.56]       Stack Trace:</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:05:28.56]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:05:28.56]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:05:28.56]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:06:00.60]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:00.60]       Stack Trace:</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:00.60]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:00.60]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:06:00.60]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:06:32.63]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:32.63]       Stack Trace:</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:32.63]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:32.63]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:06:32.63]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:07:04.66]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:07:04.66]       Stack Trace:</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:07:04.66]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:07:04.66]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:07:04.66]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:07:36.69]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:07:36.69]       Stack Trace:</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:07:36.69]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:07:36.69]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:07:36.69]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:08:08.75]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:08:08.75]       Stack Trace:</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:08:08.75]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:08:08.75]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(106,0): at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent()</span><br><span>[xUnit.net 00:08:08.75]         --- End of stack trace from previous location ---</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 55f63a91-b704-4244-9c15-e748397d8439</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 55f63a91-b704-4244-9c15-e748397d8439</span><br><span>Server Output: Server cache enabled = True</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: 5a454542-d294-4ce6-a864-6b099dcf0519) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: 5a454542-d294-4ce6-a864-6b099dcf0519</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received FileData request (requestId: e1c8b3c0-b2d0-441b-a837-c995f48e7437) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent file chunk of size 20 bytes for file: testfile.txt, requestId: e1c8b3c0-b2d0-441b-a837-c995f48e7437</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Completed file data transfer for file: testfile.txt, requestId: e1c8b3c0-b2d0-441b-a837-c995f48e7437</span><br><span>Inheritance is already disabled.</span><br><span>Second Response Status: 200</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = False</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: cd4e53a6-8d50-4710-8747-28fee3594587) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: cd4e53a6-8d50-4710-8747-28fee3594587</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received FileData request (requestId: 3364b7db-e4df-464c-abec-881aa878200d) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent file chunk of size 20 bytes for file: testfile.txt, requestId: 3364b7db-e4df-464c-abec-881aa878200d</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Completed file data transfer for file: testfile.txt, requestId: 3364b7db-e4df-464c-abec-881aa878200d</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: 0078c720-080c-4c24-a8e4-fd651b04d35d) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: 0078c720-080c-4c24-a8e4-fd651b04d35d</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received FileData request (requestId: 2670b81b-6659-4228-905a-045be2e96634) for file: testfile.txt</span><br><span>Client Output: fail: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Access denied to file 'testfile.txt'.</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:08:35.69]   Finished:    FileSyncServer.Tests</span><br></div>
    <div>
      <h2>Error and Warning messages</h2><span>[xUnit.net 00:00:58.47]     Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics [FAIL]</span><br><span>[xUnit.net 00:01:42.88]     Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:02:31.50]     FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:03:07.58]     FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:03:52.43]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:04:24.50]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:04:56.53]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt") [FAIL]</span><br><span>[xUnit.net 00:05:28.56]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt") [FAIL]</span><br><span>[xUnit.net 00:06:00.60]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt") [FAIL]</span><br><span>[xUnit.net 00:06:32.63]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt") [FAIL]</span><br><span>[xUnit.net 00:07:04.66]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt") [FAIL]</span><br><span>[xUnit.net 00:07:36.69]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt") [FAIL]</span><br><span>[xUnit.net 00:08:08.75]     Server.FileFetchingTests.GetLargeFile_ReturnsFileContent [FAIL]</span><br></div>
  </body>
  <style>
        body { font-family: Calibri, Verdana, Arial, sans-serif; background-color: White; color: Black; }
        h2 {
        margin-top: 15px;
        margin-bottom:10px;
        }
        pre {
        white-space: pre-wrap;
        }
        .summary {font-family:monospace;
        display: -webkit-flex; /* Safari */
        -webkit-flex-wrap: wrap; /* Safari 6.1+ */
        display: flex;
        flex-wrap: wrap;
        }
        .row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#d7e9fa;
        }
        .list-row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#ffffff;
        }
        .inner-row{
        border: 2px solid #ffffff;
        padding-left:1%;
        margin-left:1%;
        background-color:#ffffff;
        }
        .block{
        width : 150px;
        }
        .leaf-division{
        border: 2px solid #ffffff;
        background-color:#e6eff7;
        }
        .pass { color: #0c0; }
        .fail { color: #c00; }
        .error-message { color : brown; }
        .error-stack-trace { color: brown; }
        .duration {float:right;padding-right:1%;}
        .total-tests { font-size : 30px}
        .test-run-time { font-size : 30px}
        .pass-percentage { font-size : 30px}
        .error-info{
        margin-left:16px;
        }
      </style>
</html>