<html xmlns:tp="http://schemas.datacontract.org/2004/07/Microsoft.VisualStudio.TestPlatform.Extensions.HtmlLogger.ObjectModel" xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
  <body>
    <h1>Test run details</h1>
    <div class="summary">
      <div class="block"><span>Total tests</span><div class="total-tests">15</div><br></div>
      <div class="block"><span>Passed  : </span><span class="passedTests">0</span><br><span>Failed  : </span><span class="failedTests">15</span><br><span>Skipped : </span><span class="skippedTests">0</span><br></div>
      <div class="block"><span>Pass percentage</span><div class="pass-percentage">0 %</div><br></div>
      <div class="block"><span>Run duration</span><div class="test-run-time">10m 35s</div><br></div><br></div>
    <h2>Failed Results</h2><details open=""><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="-339410512-failedResult">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>36s 496ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 88
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>1m 6s</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 62
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>37s 655ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/310d1eeb-988e-4ce9-8b07-9719679f6252/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 70
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 107
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>1m 4s</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/310d1eeb-988e-4ce9-8b07-9719679f6252/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 130
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 154
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 559ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 74ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client 'e878cdb8-f5d8-4b79-a9ea-553ba01431d1'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>33s 304ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 88ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 89
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>32s 51ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>32s 33ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>32s 42ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>32s 35ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>32s 27ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>32s 32ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>32s 36ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 106
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><h2>All Results</h2><details><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="-339410512">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>36s 496ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 88
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>1m 6s</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs:line 62
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>37s 655ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/310d1eeb-988e-4ce9-8b07-9719679f6252/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 70
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 107
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>1m 4s</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/310d1eeb-988e-4ce9-8b07-9719679f6252/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 130
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 154
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 559ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 74ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client 'e878cdb8-f5d8-4b79-a9ea-553ba01431d1'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>33s 304ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 88ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 89
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>32s 51ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>32s 33ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>32s 42ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>32s 35ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>32s 27ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>32s 32ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>32s 36ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 106
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><div>
      <h2>Informational messages</h2><span>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 9.0.0-rc.1.24431.7)</span><br><span>[xUnit.net 00:00:00.50]   Discovering: FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.54]   Discovered:  FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.54]   Starting:    FileSyncServer.Tests</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: fabd12a2-84c4-4d40-b3fc-f31d26f7101d</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: fabd12a2-84c4-4d40-b3fc-f31d26f7101d</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = False</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:00:50.30]       Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:00:50.30]       Stack Trace:</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:00:50.30]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:00:50.30]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs(88,0): at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:00:50.30]         --- End of stack trace from previous location ---</span><br><span>Server Output: Server cache enabled = True</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 0/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 0/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:01:56.39]       Expected response1.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:01:56.39]       Stack Trace:</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:01:56.39]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:01:56.39]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ServerCaching.cs(62,0): at FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:01:56.39]         --- End of stack trace from previous location ---</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 310d1eeb-988e-4ce9-8b07-9719679f6252</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 310d1eeb-988e-4ce9-8b07-9719679f6252</span><br><span>Server Output: Server cache enabled = True</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:02:46.54]       System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/310d1eeb-988e-4ce9-8b07-9719679f6252/testfile.txt", waiting until "networkidle"</span><br><span>[xUnit.net 00:02:46.54]       Stack Trace:</span><br><span>[xUnit.net 00:02:46.54]         /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)</span><br><span>[xUnit.net 00:02:46.54]         /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)</span><br><span>[xUnit.net 00:02:46.54]         /_/src/Playwright/Core/Frame.cs(793,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)</span><br><span>[xUnit.net 00:02:46.54]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(70,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:02:46.54]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(107,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:02:46.54]         --- End of stack trace from previous location ---</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = False</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 0/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 0/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:03:51.11]       System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/310d1eeb-988e-4ce9-8b07-9719679f6252/testfile.txt", waiting until "networkidle"</span><br><span>[xUnit.net 00:03:51.11]       Stack Trace:</span><br><span>[xUnit.net 00:03:51.11]         /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)</span><br><span>[xUnit.net 00:03:51.11]         /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)</span><br><span>[xUnit.net 00:03:51.11]         /_/src/Playwright/Core/Frame.cs(793,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)</span><br><span>[xUnit.net 00:03:51.11]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(130,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:03:51.11]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(154,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:03:51.11]         --- End of stack trace from previous location ---</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 23cb8926-40e5-4fed-b1ec-36a783a60d30</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 23cb8926-40e5-4fed-b1ec-36a783a60d30</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 969ab08e-54ac-4364-a740-43d25f8ada06</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 969ab08e-54ac-4364-a740-43d25f8ada06</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 4e518df7-9d79-4d86-a792-1ab8dc320024</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 4e518df7-9d79-4d86-a792-1ab8dc320024</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 326cbda9-9ec9-45e7-9a36-011085d26504</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 326cbda9-9ec9-45e7-9a36-011085d26504</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 6268f046-aa02-4a1d-b167-5a63e5e44c7f</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 6268f046-aa02-4a1d-b167-5a63e5e44c7f</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 11e7c390-06a4-48f5-8e6c-152f7bc7105c</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test1.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test2.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test3.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test4.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test5.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 11e7c390-06a4-48f5-8e6c-152f7bc7105c</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Disposed client with clientId: 23cb8926-40e5-4fed-b1ec-36a783a60d30</span><br><span>Disposed client with clientId: 969ab08e-54ac-4364-a740-43d25f8ada06</span><br><span>Disposed client with clientId: 4e518df7-9d79-4d86-a792-1ab8dc320024</span><br><span>Disposed client with clientId: 326cbda9-9ec9-45e7-9a36-011085d26504</span><br><span>Disposed client with clientId: 6268f046-aa02-4a1d-b167-5a63e5e44c7f</span><br><span>[xUnit.net 00:04:47.99]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:04:47.99]       Stack Trace:</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:04:47.99]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:04:47.99]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(124,0): at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics()</span><br><span>[xUnit.net 00:04:47.99]         --- End of stack trace from previous location ---</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: e878cdb8-f5d8-4b79-a9ea-553ba01431d1</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: e878cdb8-f5d8-4b79-a9ea-553ba01431d1</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: cab4f2fb-a19a-4ebc-a641-146bb177a7ec</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: cab4f2fb-a19a-4ebc-a641-146bb177a7ec</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: e5658cae-c9c8-48b7-8013-aeb445d9e331</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: e5658cae-c9c8-48b7-8013-aeb445d9e331</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: e44ceee9-558c-42bd-8b59-03710839205d</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: e44ceee9-558c-42bd-8b59-03710839205d</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 24aa0ea8-29de-45a2-8b34-c074a966899a</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test1.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 24aa0ea8-29de-45a2-8b34-c074a966899a</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test10.txt</span><br><span>Disposed client with clientId: e878cdb8-f5d8-4b79-a9ea-553ba01431d1</span><br><span>Disposed client with clientId: cab4f2fb-a19a-4ebc-a641-146bb177a7ec</span><br><span>Disposed client with clientId: e5658cae-c9c8-48b7-8013-aeb445d9e331</span><br><span>Disposed client with clientId: e44ceee9-558c-42bd-8b59-03710839205d</span><br><span>Disposed client with clientId: 24aa0ea8-29de-45a2-8b34-c074a966899a</span><br><span>[xUnit.net 00:05:32.37]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client 'e878cdb8-f5d8-4b79-a9ea-553ba01431d1'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:05:32.37]       Stack Trace:</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:05:32.37]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:05:32.37]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(196,0): at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:05:32.37]         --- End of stack trace from previous location ---</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 748fb709-99ae-4406-bdd7-d36bf9cf7a48</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 748fb709-99ae-4406-bdd7-d36bf9cf7a48</span><br><span>[xUnit.net 00:06:18.15]       Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:18.15]       Stack Trace:</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:18.15]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:18.15]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(136,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:06:18.15]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:06:50.24]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:50.24]       Stack Trace:</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:50.24]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:50.24]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(89,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:06:50.24]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:07:22.29]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:07:22.29]       Stack Trace:</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:07:22.29]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:07:22.29]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:07:22.29]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:07:54.32]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:07:54.32]       Stack Trace:</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:07:54.32]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:07:54.32]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:07:54.32]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:08:26.37]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:08:26.37]       Stack Trace:</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:08:26.37]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:08:26.37]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:08:26.37]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:08:58.40]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:08:58.40]       Stack Trace:</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:08:58.40]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:08:58.40]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:08:58.40]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:09:30.43]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:09:30.43]       Stack Trace:</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:09:30.43]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:09:30.43]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:09:30.43]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:10:02.46]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:10:02.46]       Stack Trace:</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:10:02.46]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:10:02.46]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:10:02.46]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:10:34.50]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:10:34.50]       Stack Trace:</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:10:34.50]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:10:34.50]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(106,0): at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent()</span><br><span>[xUnit.net 00:10:34.50]         --- End of stack trace from previous location ---</span><br><span>Client Output: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.")</span><br><span>[xUnit.net 00:10:34.52]   Finished:    FileSyncServer.Tests</span><br></div>
    <div>
      <h2>Error and Warning messages</h2><span>[xUnit.net 00:00:50.30]     FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:01:56.39]     FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:02:46.54]     FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:03:51.11]     FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:04:47.99]     Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics [FAIL]</span><br><span>[xUnit.net 00:05:32.37]     Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:06:18.15]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:06:50.24]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:07:22.29]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt") [FAIL]</span><br><span>[xUnit.net 00:07:54.32]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt") [FAIL]</span><br><span>[xUnit.net 00:08:26.37]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt") [FAIL]</span><br><span>[xUnit.net 00:08:58.40]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt") [FAIL]</span><br><span>[xUnit.net 00:09:30.43]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt") [FAIL]</span><br><span>[xUnit.net 00:10:02.46]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt") [FAIL]</span><br><span>[xUnit.net 00:10:34.50]     Server.FileFetchingTests.GetLargeFile_ReturnsFileContent [FAIL]</span><br></div>
  </body>
  <style>
        body { font-family: Calibri, Verdana, Arial, sans-serif; background-color: White; color: Black; }
        h2 {
        margin-top: 15px;
        margin-bottom:10px;
        }
        pre {
        white-space: pre-wrap;
        }
        .summary {font-family:monospace;
        display: -webkit-flex; /* Safari */
        -webkit-flex-wrap: wrap; /* Safari 6.1+ */
        display: flex;
        flex-wrap: wrap;
        }
        .row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#d7e9fa;
        }
        .list-row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#ffffff;
        }
        .inner-row{
        border: 2px solid #ffffff;
        padding-left:1%;
        margin-left:1%;
        background-color:#ffffff;
        }
        .block{
        width : 150px;
        }
        .leaf-division{
        border: 2px solid #ffffff;
        background-color:#e6eff7;
        }
        .pass { color: #0c0; }
        .fail { color: #c00; }
        .error-message { color : brown; }
        .error-stack-trace { color: brown; }
        .duration {float:right;padding-right:1%;}
        .total-tests { font-size : 30px}
        .test-run-time { font-size : 30px}
        .pass-percentage { font-size : 30px}
        .error-info{
        margin-left:16px;
        }
      </style>
</html>