<html xmlns:tp="http://schemas.datacontract.org/2004/07/Microsoft.VisualStudio.TestPlatform.Extensions.HtmlLogger.ObjectModel" xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
  <body>
    <h1>Test run details</h1>
    <div class="summary">
      <div class="block"><span>Total tests</span><div class="total-tests">15</div><br></div>
      <div class="block"><span>Passed  : </span><span class="passedTests">2</span><br><span>Failed  : </span><span class="failedTests">13</span><br><span>Skipped : </span><span class="skippedTests">0</span><br></div>
      <div class="block"><span>Pass percentage</span><div class="pass-percentage">13 %</div><br></div>
      <div class="block"><span>Run duration</span><div class="test-run-time">8m 35s</div><br></div><br></div>
    <h2>Failed Results</h2><details open=""><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="-1709829854-failedResult">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>37s 906ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/4dea2be2-7c37-4540-97f9-d8229eb947c8/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 70
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 107
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>34s 521ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/4dea2be2-7c37-4540-97f9-d8229eb947c8/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 130
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 154
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 637ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 100ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '7206d931-e2d4-4eda-8c5c-3615b62b87e2'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>32s 767ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 103ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 89
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>32s 68ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>32s 58ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>32s 54ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>32s 46ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>32s 52ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>32s 48ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>32s 46ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 106
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><h2>All Results</h2><details><summary>C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\FileSyncServer.Tests.dll</summary><div class="inner-row" Id="-1709829854">
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>37s 906ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/4dea2be2-7c37-4540-97f9-d8229eb947c8/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 70
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 107
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>34s 521ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/4dea2be2-7c37-4540-97f9-d8229eb947c8/testfile.txt", waiting until "networkidle"</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 793
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 130
   at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs:line 154
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="pass">✔</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Disabled_Should_Fail_After_Permission_Revoked​</span><div class="duration"><span>6s 149ms</span><br></div>
          </div>
          <div class="error-info"></div>
        </div>
        <div class="leaf-division">
          <div><span class="pass">✔</span><span> FileSyncServer.Tests.ServerCachingTests.Server_Cache_Enabled_Should_Serve_File_After_Permission_Revoked​</span><div class="duration"><span>6s 146ms</span><br></div>
          </div>
          <div class="error-info"></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics​</span><div class="duration"><span>34s 637ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 124
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 100ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '7206d931-e2d4-4eda-8c5c-3615b62b87e2'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs:line 196
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses​</span><div class="duration"><span>32s 767ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 136
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses​</span><div class="duration"><span>32s 103ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs:line 89
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt")​</span><div class="duration"><span>32s 68ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt")​</span><div class="duration"><span>32s 58ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt")​</span><div class="duration"><span>32s 54ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 81
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt")​</span><div class="duration"><span>32s 46ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt")​</span><div class="duration"><span>32s 52ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt")​</span><div class="duration"><span>32s 48ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName) in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 61
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
        <div class="leaf-division">
          <div><span class="fail">✘</span><span> Server.FileFetchingTests.GetLargeFile_ReturnsFileContent​</span><div class="duration"><span>32s 46ms</span><br></div>
          </div>
          <div class="error-info">
    Error: <span class="error-message"><pre>Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</pre></span><br>
    Stack trace: <span class="error-stack-trace"><pre>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent() in C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs:line 106
--- End of stack trace from previous location ---</pre></span><br></div>
        </div>
      </div></details><div>
      <h2>Informational messages</h2><span>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 9.0.0-rc.1.24431.7)</span><br><span>[xUnit.net 00:00:00.57]   Discovering: FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.59]   Discovered:  FileSyncServer.Tests</span><br><span>[xUnit.net 00:00:00.60]   Starting:    FileSyncServer.Tests</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 4dea2be2-7c37-4540-97f9-d8229eb947c8</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 4dea2be2-7c37-4540-97f9-d8229eb947c8</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Server cache enabled = True</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:00:51.80]       System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/4dea2be2-7c37-4540-97f9-d8229eb947c8/testfile.txt", waiting until "networkidle"</span><br><span>[xUnit.net 00:00:51.80]       Stack Trace:</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>[xUnit.net 00:00:51.80]         /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)</span><br><span>[xUnit.net 00:00:51.80]         /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)</span><br><span>[xUnit.net 00:00:51.80]         /_/src/Playwright/Core/Frame.cs(793,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)</span><br><span>[xUnit.net 00:00:51.80]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(70,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:00:51.80]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(107,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked()</span><br><span>[xUnit.net 00:00:51.80]         --- End of stack trace from previous location ---</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = False</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>[xUnit.net 00:01:26.33]       System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - navigating to "https://localhost:5001/4dea2be2-7c37-4540-97f9-d8229eb947c8/testfile.txt", waiting until "networkidle"</span><br><span>[xUnit.net 00:01:26.33]       Stack Trace:</span><br><span>[xUnit.net 00:01:26.33]         /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)</span><br><span>[xUnit.net 00:01:26.33]         /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)</span><br><span>[xUnit.net 00:01:26.33]         /_/src/Playwright/Core/Frame.cs(793,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)</span><br><span>[xUnit.net 00:01:26.33]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(130,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:01:26.33]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ClientCaching.cs(154,0): at FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked()</span><br><span>[xUnit.net 00:01:26.33]         --- End of stack trace from previous location ---</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 4ac745ac-9e9d-46ca-84ed-3aa2bc181ad4</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 4ac745ac-9e9d-46ca-84ed-3aa2bc181ad4</span><br><span>Server Output: Server cache enabled = False</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: c904de70-174f-4b15-baf7-233871e20be3) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: c904de70-174f-4b15-baf7-233871e20be3</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received FileData request (requestId: 5bd3076b-e60a-4fbb-bb5c-57132991cfd9) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent file chunk of size 20 bytes for file: testfile.txt, requestId: 5bd3076b-e60a-4fbb-bb5c-57132991cfd9</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Completed file data transfer for file: testfile.txt, requestId: 5bd3076b-e60a-4fbb-bb5c-57132991cfd9</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: 9348cd59-13aa-4d7f-98a9-e4b4bba8db1f) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: 9348cd59-13aa-4d7f-98a9-e4b4bba8db1f</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received FileData request (requestId: 382c80a1-738f-44ca-96c8-d726cc1f2641) for file: testfile.txt</span><br><span>Client Output: fail: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Access denied to file 'testfile.txt'.</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Read and Delete permissions for OMEN\budcr are already granted.</span><br><span>Inheritance disabled and inherited rules removed.</span><br><span>Server Output: Server cache enabled = True</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: b6dfe031-d20f-4c86-a1bf-bc7f60ef462d) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: b6dfe031-d20f-4c86-a1bf-bc7f60ef462d</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received FileData request (requestId: 75110b48-9fac-45df-9857-1a4c074187a7) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent file chunk of size 20 bytes for file: testfile.txt, requestId: 75110b48-9fac-45df-9857-1a4c074187a7</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Completed file data transfer for file: testfile.txt, requestId: 75110b48-9fac-45df-9857-1a4c074187a7</span><br><span>Inheritance is already disabled.</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Received MetaData request (requestId: db56b2c6-2338-48b8-9876-c4d0d0bbbda6) for file: testfile.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent metadata for file: testfile.txt, requestId: db56b2c6-2338-48b8-9876-c4d0d0bbbda6</span><br><span>Granted Read and Delete permissions to OMEN\budcr.</span><br><span>Inheritance is already disabled.</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: b521aa3e-80a3-4408-a62c-dc1e3735d039</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: b521aa3e-80a3-4408-a62c-dc1e3735d039</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 63e9b41c-1a10-4238-a2cd-2115affc61cd</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 63e9b41c-1a10-4238-a2cd-2115affc61cd</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 483244c1-ff51-4636-b2ea-44254cf04dd5</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 483244c1-ff51-4636-b2ea-44254cf04dd5</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 0ca639c0-f387-45d7-8433-2e043f5ec06d</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 0ca639c0-f387-45d7-8433-2e043f5ec06d</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: b82dcdd8-14f4-4279-8aec-84dc99f34b89</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: b82dcdd8-14f4-4279-8aec-84dc99f34b89</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 94808090-eeca-43b6-b6a3-d86ee700c7fc</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test1.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test2.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test3.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test4.txt</span><br><span>Created large test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\performance_test5.txt</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 94808090-eeca-43b6-b6a3-d86ee700c7fc</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 2/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 2/768 (Min: 0)</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>Disposed client with clientId: b521aa3e-80a3-4408-a62c-dc1e3735d039</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 63e9b41c-1a10-4238-a2cd-2115affc61cd</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 483244c1-ff51-4636-b2ea-44254cf04dd5</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 0ca639c0-f387-45d7-8433-2e043f5ec06d</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: b82dcdd8-14f4-4279-8aec-84dc99f34b89</span><br><span>[xUnit.net 00:02:48.23]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file 'largeFile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:02:48.23]       Stack Trace:</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:02:48.23]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:02:48.23]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(124,0): at Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics()</span><br><span>[xUnit.net 00:02:48.23]         --- End of stack trace from previous location ---</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 7206d931-e2d4-4eda-8c5c-3615b62b87e2</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 7206d931-e2d4-4eda-8c5c-3615b62b87e2</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: dbb21cb0-96de-48e8-b22e-fb77b5a21c22</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: dbb21cb0-96de-48e8-b22e-fb77b5a21c22</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 76f346c7-d097-411a-a58b-459a0ac92083</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 76f346c7-d097-411a-a58b-459a0ac92083</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 45300d3c-e0ff-4a26-979c-223b1be29260</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 45300d3c-e0ff-4a26-979c-223b1be29260</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 6949b3e2-f02c-440e-ab9c-d319cfc9b1fe</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 6949b3e2-f02c-440e-ab9c-d319cfc9b1fe</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\0\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\1\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\2\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\3\test10.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test1.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test2.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test3.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test4.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test5.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test6.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test7.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test8.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test9.txt</span><br><span>Created test file: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\4\test10.txt</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 7206d931-e2d4-4eda-8c5c-3615b62b87e2</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: dbb21cb0-96de-48e8-b22e-fb77b5a21c22</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 76f346c7-d097-411a-a58b-459a0ac92083</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 45300d3c-e0ff-4a26-979c-223b1be29260</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>Disposed client with clientId: 6949b3e2-f02c-440e-ab9c-d319cfc9b1fe</span><br><span>[xUnit.net 00:03:32.77]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for file '0\test1.txt' from client '7206d931-e2d4-4eda-8c5c-3615b62b87e2'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:03:32.77]       Stack Trace:</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:03:32.77]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:03:32.77]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\PerformanceTests .cs(196,0): at Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:03:32.77]         --- End of stack trace from previous location ---</span><br><span>Server started...</span><br><span>Client Output: Starting FileClient...</span><br><span>Client Output: Checking server health...</span><br><span>Client Output: Server is healthy.</span><br><span>Client Output: Temporary directory already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test1.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test2.txt</span><br><span>Client Output: Test file already exists: C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\bin\Debug\net9.0\client_cache\test3.txt</span><br><span>Client Output: File synchronization initiated.</span><br><span>Client started with clientId: 7073909b-85bd-4a7b-9a0f-75bd0c50acf8</span><br><span>Client Output: info: FileSyncClient.Services.ClientFileSyncManager[0]</span><br><span>Client Output:       Sent Init response to server with clientGuid: 7073909b-85bd-4a7b-9a0f-75bd0c50acf8</span><br><span>Server Output: ThreadPool Stats:</span><br><span>Server Output: Worker Threads in Use: 1/768 (Min: 0)</span><br><span>Server Output: Completion Port Threads in Use: 1/768 (Min: 0)</span><br><span>[xUnit.net 00:04:18.04]       Expected result.Status to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:04:18.04]       Stack Trace:</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:04:18.04]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:04:18.04]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(136,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:04:18.04]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:04:50.14]       Expected result.Status to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:04:50.14]       Stack Trace:</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:04:50.14]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:04:50.14]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\ConcurrentRequestsTests .cs(89,0): at Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses()</span><br><span>[xUnit.net 00:04:50.14]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:05:22.21]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'unknownfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:05:22.21]       Stack Trace:</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:05:22.21]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:05:22.21]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:05:22.21]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:05:54.27]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:05:54.27]       Stack Trace:</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:05:54.27]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:05:54.27]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:05:54.27]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:06:26.33]       Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404} because Expected status code 404 for non-existing file 'nonexistent2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:26.33]       Stack Trace:</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:26.33]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:26.33]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(81,0): at Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(String fileName)</span><br><span>[xUnit.net 00:06:26.33]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:06:58.37]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test3.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:06:58.37]       Stack Trace:</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:06:58.37]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:06:58.37]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:06:58.37]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:07:30.43]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test2.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:07:30.43]       Stack Trace:</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:07:30.43]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:07:30.43]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:07:30.43]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:08:02.48]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for existing file 'test1.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:08:02.48]       Stack Trace:</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:08:02.48]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:08:02.48]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(61,0): at Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(String fileName)</span><br><span>[xUnit.net 00:08:02.48]         --- End of stack trace from previous location ---</span><br><span>[xUnit.net 00:08:34.52]       Expected response.StatusCode to be HttpStatusCode.OK {value: 200} because Expected status code 200 for large file 'largeemptyfile.txt'., but found HttpStatusCode.InternalServerError {value: 500}.</span><br><span>[xUnit.net 00:08:34.52]       Stack Trace:</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)</span><br><span>[xUnit.net 00:08:34.52]            at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)</span><br><span>[xUnit.net 00:08:34.52]         C:\Users\budcr\source\repos\RemoteBlazorWebView\src\Benchmarks\FilePOC\FileSyncServer.Tests\FileFetchingTests.cs(106,0): at Server.FileFetchingTests.GetLargeFile_ReturnsFileContent()</span><br><span>[xUnit.net 00:08:34.52]         --- End of stack trace from previous location ---</span><br><span>Client Output: Status(StatusCode="Internal", Detail="Internal server error.")</span><br><span>[xUnit.net 00:08:34.55]   Finished:    FileSyncServer.Tests</span><br></div>
    <div>
      <h2>Error and Warning messages</h2><span>[xUnit.net 00:00:51.80]     FileSyncServer.Tests.ClientCachingTests.Client_Cache_Enabled_Should_Serve_File_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:01:26.33]     FileSyncServer.Tests.ClientCachingTests.Client_Cache_Disabled_Should_Fail_After_Permission_Revoked [FAIL]</span><br><span>[xUnit.net 00:02:48.23]     Server.PerformanceTests.FetchLargeFiles_PerformanceMetrics [FAIL]</span><br><span>[xUnit.net 00:03:32.77]     Server.PerformanceTests.MultipleClientsConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:04:18.04]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequestsWithSameFile_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:04:50.14]     Server.ConcurrentRequestsTests.MultipleConcurrentFileRequests_ReturnsCorrectResponses [FAIL]</span><br><span>[xUnit.net 00:05:22.21]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "unknownfile.txt") [FAIL]</span><br><span>[xUnit.net 00:05:54.27]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent1.txt") [FAIL]</span><br><span>[xUnit.net 00:06:26.33]     Server.FileFetchingTests.GetNonExistingFile_ReturnsNotFound(fileName: "nonexistent2.txt") [FAIL]</span><br><span>[xUnit.net 00:06:58.37]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test3.txt") [FAIL]</span><br><span>[xUnit.net 00:07:30.43]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test2.txt") [FAIL]</span><br><span>[xUnit.net 00:08:02.48]     Server.FileFetchingTests.GetExistingFile_ReturnsFileContent(fileName: "test1.txt") [FAIL]</span><br><span>[xUnit.net 00:08:34.52]     Server.FileFetchingTests.GetLargeFile_ReturnsFileContent [FAIL]</span><br></div>
  </body>
  <style>
        body { font-family: Calibri, Verdana, Arial, sans-serif; background-color: White; color: Black; }
        h2 {
        margin-top: 15px;
        margin-bottom:10px;
        }
        pre {
        white-space: pre-wrap;
        }
        .summary {font-family:monospace;
        display: -webkit-flex; /* Safari */
        -webkit-flex-wrap: wrap; /* Safari 6.1+ */
        display: flex;
        flex-wrap: wrap;
        }
        .row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#d7e9fa;
        }
        .list-row {
        border: 2px solid #ffffff;
        width:100%;
        cursor:pointer;
        background-color:#ffffff;
        }
        .inner-row{
        border: 2px solid #ffffff;
        padding-left:1%;
        margin-left:1%;
        background-color:#ffffff;
        }
        .block{
        width : 150px;
        }
        .leaf-division{
        border: 2px solid #ffffff;
        background-color:#e6eff7;
        }
        .pass { color: #0c0; }
        .fail { color: #c00; }
        .error-message { color : brown; }
        .error-stack-trace { color: brown; }
        .duration {float:right;padding-right:1%;}
        .total-tests { font-size : 30px}
        .test-run-time { font-size : 30px}
        .pass-percentage { font-size : 30px}
        .error-info{
        margin-left:16px;
        }
      </style>
</html>